load("//go:def.bzl", "go_library", "go_prefix")

go_prefix("github.com/bazelbuild/rules_go")

go_library(
    name = "go_default_library",
    srcs = glob(["*.go"]),
    visibility = ["//visibility:public"],
)
